using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SSC.Generators;

[Generator]
public sealed class ParallelViewGenerator : IIncrementalGenerator
{
    private const string GenerateViewAttributeMetadataName = "SSC.GenerateParallelViewAttribute";
    private const string CompareIgnoreAttributeMetadataName = "SSC.CompareIgnoreAttribute";
    private const string DictionaryMetadataName = "System.Collections.Generic.IDictionary<TKey, TValue>";
    private const string ReadOnlyDictionaryMetadataName = "System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>";
    private const string EnumerableMetadataName = "System.Collections.Generic.IEnumerable<T>";

    private static readonly SymbolDisplayFormat TypeDisplayFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor UnsupportedGenericRootRule = new(
        id: "SSCGEN001",
        title: "Generic root type is not supported",
        messageFormat: "GenerateParallelView does not support generic type '{0}'.",
        category: "SSC.Generators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var roots = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateViewAttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (generatorContext, _) => (INamedTypeSymbol)generatorContext.TargetSymbol)
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(roots.Collect(), static (productionContext, symbols) =>
        {
            Execute(productionContext, symbols);
        });
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> symbols)
    {
        if (symbols.IsDefaultOrEmpty)
        {
            return;
        }

        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var root in symbols)
        {
            if (!seen.Add(root))
            {
                continue;
            }

            if (root.TypeParameters.Length > 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedGenericRootRule,
                    root.Locations.FirstOrDefault(),
                    root.ToDisplayString()));
                continue;
            }

            var source = GenerateRootSource(root);
            var hintName = $"{SanitizeIdentifier(root.ToDisplayString(TypeDisplayFormat))}.ParallelGenerated.g.cs";
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateRootSource(INamedTypeSymbol rootType)
    {
        var graph = BuildTypeGraph(rootType);
        var rootPrefix = SanitizeIdentifier(rootType.ToDisplayString(TypeDisplayFormat));
        var viewNames = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);

        foreach (var typeShape in graph)
        {
            var typeToken = SanitizeIdentifier(typeShape.Type.ToDisplayString(TypeDisplayFormat));
            viewNames[typeShape.Type] = $"{rootPrefix}_{typeToken}_View";
        }

        var rootViewName = viewNames[rootType];
        var rootTypeName = rootType.ToDisplayString(TypeDisplayFormat);

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace SSC.Generated;");
        source.AppendLine();
        source.AppendLine($"internal static class {rootPrefix}_GeneratedViewExtensions");
        source.AppendLine("{");
        source.AppendLine($"    internal static {rootViewName}? AsGeneratedView(this global::SSC.CompareResult<{rootTypeName}> result)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(result);");
        source.AppendLine("        if (result.Root is null)");
        source.AppendLine("        {");
        source.AppendLine("            return null;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var parallelNode = global::SSC.ParallelGeneratedRuntime.RequireNode(result.Root, nameof(AsGeneratedView));");
        source.AppendLine($"        return new {rootViewName}(parallelNode);");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();

        foreach (var typeShape in graph)
        {
            AppendViewClass(source, typeShape, viewNames[typeShape.Type], viewNames);
            source.AppendLine();
        }

        return source.ToString();
    }

    private static void AppendViewClass(
        StringBuilder source,
        TypeShape typeShape,
        string viewName,
        IReadOnlyDictionary<INamedTypeSymbol, string> viewNames)
    {
        var modelTypeName = typeShape.Type.ToDisplayString(TypeDisplayFormat);
        source.AppendLine($"internal sealed class {viewName}");
        source.AppendLine("{");
        source.AppendLine($"    private readonly global::SSC.ParallelNode<{modelTypeName}> _node;");
        source.AppendLine();
        source.AppendLine($"    internal {viewName}(global::SSC.ParallelNode<{modelTypeName}> node)");
        source.AppendLine("    {");
        source.AppendLine("        _node = node;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine($"    public {modelTypeName}? this[int modelIndex] => _node[modelIndex];");
        source.AppendLine();
        source.AppendLine("    public global::SSC.ParallelGeneratedMeta NodeMeta => new(_node);");
        source.AppendLine();
        if (!typeShape.Members.Any(static member => string.Equals(member.MemberName, "GetState", StringComparison.Ordinal)))
        {
            source.AppendLine("    public global::SSC.ValueState GetState(int modelIndex) => _node.GetState(modelIndex);");
            source.AppendLine();
        }

        if (!typeShape.Members.Any(static member => string.Equals(member.MemberName, "Select", StringComparison.Ordinal)))
        {
            source.AppendLine("    public global::SSC.ParallelGeneratedValue<");
            source.AppendLine($"        {modelTypeName},");
            source.AppendLine("        TNext> Select<TNext>(global::System.Func<");
            source.AppendLine($"        {modelTypeName},");
            source.AppendLine("        TNext> selector) =>");
            source.AppendLine("        new(_node, selector);");
            source.AppendLine();
        }

        foreach (var member in typeShape.Members)
        {
            var memberName = EscapeIdentifier(member.MemberName);
            if (member.Kind == MemberKind.Container)
            {
                if (member.ElementType is null || !viewNames.TryGetValue(member.ElementType, out var childViewName))
                {
                    continue;
                }

                var elementTypeName = member.ElementType.ToDisplayString(TypeDisplayFormat);
                if (member.KeyType is not null)
                {
                    var keyTypeName = member.KeyType.ToDisplayString(TypeDisplayFormat);
                    source.AppendLine($"    public global::SSC.ParallelGeneratedDictionary<{keyTypeName}, {elementTypeName}, {childViewName}> {memberName} =>");
                    source.AppendLine($"        new(_node.GetChildren<{elementTypeName}>(nameof({modelTypeName}.{memberName})), _node.Count, static child => new {childViewName}(child));");
                }
                else
                {
                    source.AppendLine($"    public global::SSC.ParallelGeneratedList<{elementTypeName}, {childViewName}> {memberName} =>");
                    source.AppendLine($"        new(_node.GetChildren<{elementTypeName}>(nameof({modelTypeName}.{memberName})), _node.Count, static child => new {childViewName}(child));");
                }

                source.AppendLine();
                continue;
            }

            if (member.Kind == MemberKind.Object)
            {
                if (member.ObjectType is null || !viewNames.TryGetValue(member.ObjectType, out var childViewName))
                {
                    continue;
                }

                var objectTypeName = member.ObjectType.ToDisplayString(TypeDisplayFormat);
                source.AppendLine($"    public {childViewName} {memberName} =>");
                source.AppendLine($"        new(global::SSC.ParallelGeneratedRuntime.RequireMemberNode<{modelTypeName}, {objectTypeName}>(_node, nameof({modelTypeName}.{memberName}), nameof({modelTypeName}.{memberName})));");
                source.AppendLine();
                continue;
            }

            var valueTypeName = GetGeneratedValueTypeName(member.ValueType!);
            var getterExpression = GetGeneratedValueGetterExpression(memberName, member.ValueType!);
            source.AppendLine($"    public global::SSC.ParallelGeneratedValue<{modelTypeName}, {valueTypeName}> {memberName} =>");
            source.AppendLine($"        new(_node, static model => {getterExpression});");
            source.AppendLine();
        }

        source.AppendLine("}");
    }

    private static List<TypeShape> BuildTypeGraph(INamedTypeSymbol rootType)
    {
        var queue = new Queue<INamedTypeSymbol>();
        var visited = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var shapes = new List<TypeShape>();

        queue.Enqueue(rootType);
        while (queue.Count > 0)
        {
            var type = queue.Dequeue();
            if (!visited.Add(type))
            {
                continue;
            }

            var members = new List<MemberShape>();
            foreach (var property in GetComparableMembers(type))
            {
                if (TryGetDictionaryTypes(property.Type, out var dictionaryKeyType, out var dictionaryElementType)
                    && dictionaryElementType is INamedTypeSymbol dictionaryElementNamedType)
                {
                    members.Add(MemberShape.Dictionary(property.Name, dictionaryKeyType, dictionaryElementNamedType));
                    queue.Enqueue(dictionaryElementNamedType);
                    continue;
                }

                if (TryGetSequenceElementType(property.Type, out var sequenceElementType)
                    && sequenceElementType is INamedTypeSymbol sequenceElementNamedType)
                {
                    members.Add(MemberShape.Container(property.Name, sequenceElementNamedType));
                    queue.Enqueue(sequenceElementNamedType);
                    continue;
                }

                if (TryGetObjectMemberType(property.Type, out var objectMemberType))
                {
                    members.Add(MemberShape.Object(property.Name, objectMemberType));
                    queue.Enqueue(objectMemberType);
                    continue;
                }

                members.Add(MemberShape.Value(property.Name, property.Type));
            }

            shapes.Add(new TypeShape(type, members));
        }

        return shapes;
    }

    private static IEnumerable<IFieldOrPropertySymbol> GetComparableMembers(INamedTypeSymbol type)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is IPropertySymbol property)
                {
                    if (!seen.Add(property.Name))
                    {
                        continue;
                    }

                    if (property.IsStatic || property.GetMethod is null || property.Parameters.Length > 0)
                    {
                        continue;
                    }

                    if (property.DeclaredAccessibility != Accessibility.Public)
                    {
                        continue;
                    }

                    if (HasAttribute(property, CompareIgnoreAttributeMetadataName))
                    {
                        continue;
                    }

                    yield return new FieldOrPropertySymbol(property.Name, property.Type);
                    continue;
                }

                if (member is IFieldSymbol field)
                {
                    if (!seen.Add(field.Name))
                    {
                        continue;
                    }

                    if (field.IsStatic || field.DeclaredAccessibility != Accessibility.Public)
                    {
                        continue;
                    }

                    if (HasAttribute(field, CompareIgnoreAttributeMetadataName))
                    {
                        continue;
                    }

                    yield return new FieldOrPropertySymbol(field.Name, field.Type);
                }
            }
        }
    }

    private static bool HasAttribute(ISymbol symbol, string fullTypeName)
    {
        return symbol.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() == fullTypeName);
    }

    private static bool TryGetDictionaryTypes(ITypeSymbol type, out ITypeSymbol keyType, out ITypeSymbol valueType)
    {
        foreach (var candidate in EnumerateSelfAndInterfaces(type))
        {
            if (candidate is not INamedTypeSymbol named || !named.IsGenericType)
            {
                continue;
            }

            var metadataName = named.OriginalDefinition.ToDisplayString();
            if (metadataName != DictionaryMetadataName && metadataName != ReadOnlyDictionaryMetadataName)
            {
                continue;
            }

            keyType = named.TypeArguments[0];
            valueType = named.TypeArguments[1];
            return true;
        }

        keyType = null!;
        valueType = null!;
        return false;
    }

    private static bool TryGetObjectMemberType(ITypeSymbol type, out INamedTypeSymbol objectType)
    {
        if (IsScalarType(type))
        {
            objectType = null!;
            return false;
        }

        if (type is INamedTypeSymbol named
            && (named.TypeKind == TypeKind.Class || named.TypeKind == TypeKind.Struct || named.TypeKind == TypeKind.Interface)
            && named.SpecialType != SpecialType.System_Object)
        {
            objectType = named;
            return true;
        }

        objectType = null!;
        return false;
    }

    private static bool TryGetSequenceElementType(ITypeSymbol type, out ITypeSymbol elementType)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            elementType = null!;
            return false;
        }

        if (TryGetDictionaryTypes(type, out _, out _))
        {
            elementType = null!;
            return false;
        }

        if (type is IArrayTypeSymbol arrayType)
        {
            elementType = arrayType.ElementType;
            return true;
        }

        foreach (var candidate in EnumerateSelfAndInterfaces(type))
        {
            if (candidate is not INamedTypeSymbol named || !named.IsGenericType)
            {
                continue;
            }

            if (named.OriginalDefinition.ToDisplayString() != EnumerableMetadataName)
            {
                continue;
            }

            elementType = named.TypeArguments[0];
            return true;
        }

        elementType = null!;
        return false;
    }

    private static IEnumerable<ITypeSymbol> EnumerateSelfAndInterfaces(ITypeSymbol type)
    {
        yield return type;
        foreach (var @interface in type.AllInterfaces)
        {
            yield return @interface;
        }
    }

    private static string EscapeIdentifier(string identifier)
    {
        if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None)
        {
            return "@" + identifier;
        }

        return identifier;
    }

    private static string GetGeneratedValueTypeName(ITypeSymbol type)
    {
        var typeName = type.ToDisplayString(TypeDisplayFormat);
        if (type.IsValueType && !IsNullableValueType(type))
        {
            return typeName + "?";
        }

        return typeName;
    }

    private static string GetGeneratedValueGetterExpression(string escapedMemberName, ITypeSymbol type)
    {
        if (type.IsValueType && !IsNullableValueType(type))
        {
            var typeName = type.ToDisplayString(TypeDisplayFormat);
            return $"({typeName}?)model.{escapedMemberName}";
        }

        return $"model.{escapedMemberName}";
    }

    private static bool IsScalarType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && named.TypeArguments.Length == 1)
        {
            return IsScalarType(named.TypeArguments[0]);
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            return true;
        }

        return type.SpecialType is
                SpecialType.System_Boolean or
                SpecialType.System_Char or
                SpecialType.System_SByte or
                SpecialType.System_Byte or
                SpecialType.System_Int16 or
                SpecialType.System_UInt16 or
                SpecialType.System_Int32 or
                SpecialType.System_UInt32 or
                SpecialType.System_Int64 or
                SpecialType.System_UInt64 or
                SpecialType.System_Decimal or
                SpecialType.System_Single or
                SpecialType.System_Double or
                SpecialType.System_String
            || IsWellKnownScalar(type);
    }

    private static bool IsWellKnownScalar(ITypeSymbol type)
    {
        var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return fullName is
            "global::System.DateTime" or
            "global::System.DateTimeOffset" or
            "global::System.Guid" or
            "global::System.TimeSpan";
    }

    private static bool IsNullableValueType(ITypeSymbol type)
    {
        return type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
    }

    private static string SanitizeIdentifier(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return "Generated";
        }

        var builder = new StringBuilder(text.Length);
        foreach (var ch in text)
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        var sanitized = builder.ToString();
        while (sanitized.Contains("__"))
        {
            sanitized = sanitized.Replace("__", "_");
        }

        sanitized = sanitized.Trim('_');
        if (sanitized.Length == 0)
        {
            return "Generated";
        }

        if (char.IsDigit(sanitized[0]))
        {
            return "_" + sanitized;
        }

        return sanitized;
    }

    private interface IFieldOrPropertySymbol
    {
        string Name { get; }

        ITypeSymbol Type { get; }
    }

    private sealed class FieldOrPropertySymbol(string name, ITypeSymbol type) : IFieldOrPropertySymbol
    {
        public string Name { get; } = name;

        public ITypeSymbol Type { get; } = type;
    }

    private enum MemberKind
    {
        Container,
        Object,
        Value,
    }

    private sealed class TypeShape
    {
        public TypeShape(INamedTypeSymbol type, IReadOnlyList<MemberShape> members)
        {
            Type = type;
            Members = members;
        }

        public INamedTypeSymbol Type { get; }

        public IReadOnlyList<MemberShape> Members { get; }
    }

    private sealed class MemberShape
    {
        private MemberShape(
            string memberName,
            MemberKind kind,
            ITypeSymbol? keyType,
            INamedTypeSymbol? elementType,
            INamedTypeSymbol? objectType,
            ITypeSymbol? valueType)
        {
            MemberName = memberName;
            Kind = kind;
            KeyType = keyType;
            ElementType = elementType;
            ObjectType = objectType;
            ValueType = valueType;
        }

        public string MemberName { get; }

        public MemberKind Kind { get; }

        public ITypeSymbol? KeyType { get; }

        public INamedTypeSymbol? ElementType { get; }

        public INamedTypeSymbol? ObjectType { get; }

        public ITypeSymbol? ValueType { get; }

        public static MemberShape Container(string memberName, INamedTypeSymbol elementType) =>
            new(memberName, MemberKind.Container, null, elementType, null, null);

        public static MemberShape Dictionary(string memberName, ITypeSymbol keyType, INamedTypeSymbol elementType) =>
            new(memberName, MemberKind.Container, keyType, elementType, null, null);

        public static MemberShape Object(string memberName, INamedTypeSymbol objectType) =>
            new(memberName, MemberKind.Object, null, null, objectType, null);

        public static MemberShape Value(string memberName, ITypeSymbol valueType) =>
            new(memberName, MemberKind.Value, null, null, null, valueType);
    }
}
